### ISSUE TITLE
Is there any schedule for code release

### ISSUE THREAD

**Issue by KkCabin** [kevin2431/Traj-LO#1]
Nice work! Any idea when the code will be released ? Thanks

**Comment by kevin2431** [comment]
Sorry bro, I am currently dealing with some tedious things before graduation. I will try my best to release the code in this March. Thank you for following our work.

**Comment by LarryDong** [comment]
mark一下。
预祝作者毕业流程顺利，早日更新代码。如果可以，到时候这个issue里面踢一下，谢谢 :)

**Comment by kevin2431** [comment]
> mark一下。 预祝作者毕业流程顺利，早日更新代码。如果可以，到时候这个issue里面踢一下，谢谢 :)

The code is released. Feel free to test it. The current rosbag dataloader only supports one LiDAR configuration, but I will update it to support multiple LiDARs soon.

**Comment by LarryDong** [comment]
> > mark一下。 预祝作者毕业流程顺利，早日更新代码。如果可以，到时候这个issue里面踢一下，谢谢 :)
> 
> The code is released. Feel free to test it. The current rosbag dataloader only supports one LiDAR configuration, but I will update it to support multiple LiDARs soon.

Thanks!!!
