### ISSUE TITLE
Be aware of License Terms 😉

### ISSUE THREAD

**Issue by nachovizzo** [kevin2431/Traj-LO#2]
Hello, thanks for opening the source code for the benefit of the community.

I'm very happy to see many patterns we've developed with much love and effort for KISS-ICP. It definitely makes your implementation stand against the usual ones we see in LiDAR odometry.

Although I would recommend being a bit more conservative when it comes to copying code from other projects, even when you don't pay for it, there are licensing terms:
https://github.com/PRBonn/kiss-icp/blob/11c7d97d156a7ff72fefdacc3105db4a99805e0e/LICENSE#L13-L14

Just to name a few 

https://github.com/kevin2431/Traj-LO/blob/f04d15a7625bbc1167d76ddc8ef2bdcdda7d884c/include/trajlo/core/map_manager.h#L42-L59

Looks WAY too similar too
https://github.com/PRBonn/kiss-icp/blob/11c7d97d156a7ff72fefdacc3105db4a99805e0e/cpp/kiss_icp/core/VoxelHashMap.hpp#L36-L51
![image](https://github.com/kevin2431/Traj-LO/assets/21349875/a3b825ef-3f3c-43d6-9544-1eee8a149adf)

I don't mind at ALL that you reuse some code. Just be mindful of not claiming it as yours, as you claim in your license.

**Comment by kevin2431** [comment]
Thanks for reminding me this and apologize for the improper claiming in this part. The map manager of this project is inspired by your work kiss-icp. I will make it more clearer in the next commit and let you know.

Really sorry for this 😔

**Comment by nachovizzo** [comment]
No problem at all, just be sure you at least mention it, like you did with the adaptive threshold
