### ISSUE TITLE
Error Cmake

### ISSUE THREAD

**Issue by MatteoAzziniUnice** [kevin2431/Traj-LO#8]
CMake Error at thirdparty/CMakeLists.txt:30 (add_subdirectory):
  The source directory

    /PATH/Traj-LO/thirdparty/glm

  does not contain a CMakeLists.txt file.

This error appears for each subdirectory of /thirdparty after the cmake .. command in the build directory, am I doing something wrong? I have just followed the github instructions

Thanks for the attention

**Comment by kevin2431** [comment]
Make sure you have downloaded all the submodules in the `thirdparty` directory using the `--recursive` option:
```
git clone --recursive https://github.com/kevin2431/Traj-LO.git
```

**Comment by MatteoAzziniUnice** [comment]
Solved, thanks
